#!/bin/bash
# Laura Dean
# 17/10/25
# for running on the UoN HPC Ada

#SBATCH --partition=defq
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=16
#SBATCH --mem=100g
#SBATCH --time=12:00:00
#SBATCH --job-name=busco
#SBATCH --output=/gpfs01/home/mbzlld/code_and_scripts/slurm_out_scripts/slurm-%x-%j.out

# set variables
wkdir=/gpfs01/home/mbzlld/data/danionella
assembly_dir=hifiasm_asm1

assembly=ONTasm.bp.p_ctg.fasta # assemblies generated by testing of the new hifiasm version were named this
#assembly=ONTasm.bp.p_ctg_100kb.fasta # same assembly but filtered to remove fragments smaller than 100kb

lineage_dataset=actinopterygii_odb10




# load your bash profile for using conda
source $HOME/.bash_profile

# load conda environment
#conda create --name busco5.7.1 busco=5.7.1 -y
#conda activate busco5.7.1
conda activate busco

# decide what lineage dataset you will use for your species
#busco --list-datasets

# run busco
# --in : input assembly in fasta format
# --lineage_dataset nearest class in the busco database for your species
# --mode specify you are working on a genome assembly
# --out name the output files (busco will create a dfolder with this name)
# --out_path specify the path to your desired output directory
# --cpu specify number of cores to use
busco \
--in $wkdir/$assembly_dir/$assembly \
--lineage_dataset $lineage_dataset \
--mode genome \
--out buscos_${assembly%.*} \
--out_path $wkdir/$assembly_dir \
--cpu 16 \
-f

# deactivate conda
conda deactivate



